title: "Colormaps"
remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"
search_enabled: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Compiled by Pratiman Patel."